[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test-forge"
remappings = [
	"forge-std/=lib/forge-std/src/",
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
	"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
